const makeProduct = ({ specs = [], ...product }) => ({
  stock: 6,
  sales: 45,
  newRank: 20,
  brands: [product.brand],
  specs,
  longDescription: product.description,
  ...product,
})

export const expandedBuilderProducts = [
  makeProduct({ id: 'nzxt-h5-flow', brand: 'NZXT', category: 'Gabinetes', name: 'NZXT H5 Flow', description: 'Mid tower ventilado con gestión de cables y dos ventiladores incluidos.', builderNote: 'ATX · flujo directo · diseño compacto', price: 1120, image: '/products/nzxt-h5-flow.webp', formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'], maxCoolerHeight: 165, maxGpuLength: 365, maxRadiatorSize: 280, powerDraw: 8, recommended: true, specs: [['Formato', 'ATX Mid Tower'], ['GPU máxima', '365 mm'], ['Cooler máximo', '165 mm']] }),
  makeProduct({ id: 'corsair-4000d-airflow', brand: 'Corsair', category: 'Gabinetes', name: 'Corsair 4000D Airflow', description: 'Gabinete ATX con frontal de alto flujo y amplio canal posterior.', builderNote: 'ATX · gran gestión de cables', price: 1290, image: '/products/corsair-4000d-airflow.webp', formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'], maxCoolerHeight: 170, maxGpuLength: 360, maxRadiatorSize: 360, powerDraw: 10, specs: [['Formato', 'ATX Mid Tower'], ['GPU máxima', '360 mm'], ['Cooler máximo', '170 mm']] }),
  makeProduct({ id: 'lian-li-lancool-216', brand: 'Lian Li', category: 'Gabinetes', name: 'Lian Li Lancool 216', description: 'Chasis espacioso con dos ventiladores frontales de 160 mm.', builderNote: 'ATX · máximo flujo · formato amplio', price: 1490, image: '/products/lian-li-lancool-216.webp', formFactors: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'], maxCoolerHeight: 180, maxGpuLength: 392, maxRadiatorSize: 360, powerDraw: 12, specs: [['Formato', 'E-ATX / ATX'], ['GPU máxima', '392 mm'], ['Cooler máximo', '180 mm']] }),

  makeProduct({ id: 'asus-tuf-b650-plus-wifi', brand: 'ASUS', category: 'Placas madre', name: 'ASUS TUF Gaming B650-Plus WiFi', description: 'Placa AM5 ATX con DDR5, PCIe 5.0 y WiFi 6.', builderNote: 'AM5 · ATX · WiFi 6', price: 1890, image: '/products/ccl-motherboard-v2.webp', socket: 'AM5', memoryType: 'DDR5', formFactor: 'ATX', powerDraw: 58, recommended: true, specs: [['Socket', 'AM5'], ['Formato', 'ATX'], ['Memoria', 'DDR5']] }),
  makeProduct({ id: 'msi-b650m-gaming-plus', brand: 'MSI', category: 'Placas madre', name: 'MSI B650M Gaming Plus WiFi', description: 'Placa AM5 Micro-ATX compacta con DDR5 y WiFi 6E.', builderNote: 'AM5 · Micro-ATX · WiFi 6E', price: 1590, image: '/products/ccl-motherboard-v2.webp', socket: 'AM5', memoryType: 'DDR5', formFactor: 'Micro-ATX', powerDraw: 52, specs: [['Socket', 'AM5'], ['Formato', 'Micro-ATX'], ['Memoria', 'DDR5']] }),
  makeProduct({ id: 'gigabyte-b760-aorus-elite', brand: 'Gigabyte', category: 'Placas madre', name: 'Gigabyte B760 Aorus Elite AX', description: 'Placa LGA1700 ATX con DDR5, red 2.5GbE y WiFi 6E.', builderNote: 'LGA1700 · ATX · WiFi 6E', price: 1760, image: '/products/ccl-motherboard-v2.webp', socket: 'LGA1700', memoryType: 'DDR5', formFactor: 'ATX', powerDraw: 60, specs: [['Socket', 'LGA1700'], ['Formato', 'ATX'], ['Memoria', 'DDR5']] }),
  makeProduct({ id: 'asus-prime-b760m-a', brand: 'ASUS', category: 'Placas madre', name: 'ASUS Prime B760M-A WiFi', description: 'Placa LGA1700 Micro-ATX equilibrada con DDR5 y WiFi 6.', builderNote: 'LGA1700 · Micro-ATX · WiFi 6', price: 1420, image: '/products/ccl-motherboard-v2.webp', socket: 'LGA1700', memoryType: 'DDR5', formFactor: 'Micro-ATX', powerDraw: 50, specs: [['Socket', 'LGA1700'], ['Formato', 'Micro-ATX'], ['Memoria', 'DDR5']] }),

  makeProduct({ id: 'amd-ryzen-5-7600', brand: 'AMD', category: 'Procesadores', name: 'AMD Ryzen 5 7600', description: '6 núcleos y 12 hilos para gaming eficiente en plataforma AM5.', builderNote: '6 núcleos · 65W · excelente valor', price: 1780, image: '/products/builder-cpu.webp', socket: 'AM5', memoryType: 'DDR5', powerDraw: 65, performanceFactor: .9, recommended: true, specs: [['Núcleos / hilos', '6 / 12'], ['Socket', 'AM5'], ['TDP', '65W']] }),
  makeProduct({ id: 'amd-ryzen-7-7700', brand: 'AMD', category: 'Procesadores', name: 'AMD Ryzen 7 7700', description: '8 núcleos y 16 hilos con consumo contenido para gaming y creación.', builderNote: '8 núcleos · 65W · multitarea', price: 2450, image: '/products/builder-cpu.webp', socket: 'AM5', memoryType: 'DDR5', powerDraw: 88, performanceFactor: .98, specs: [['Núcleos / hilos', '8 / 16'], ['Socket', 'AM5'], ['TDP', '65W']] }),
  makeProduct({ id: 'amd-ryzen-9-7900x', brand: 'AMD', category: 'Procesadores', name: 'AMD Ryzen 9 7900X', description: '12 núcleos y 24 hilos para renderizado y trabajo intensivo.', builderNote: '12 núcleos · 170W · creación avanzada', price: 3690, image: '/products/builder-cpu.webp', socket: 'AM5', memoryType: 'DDR5', powerDraw: 170, performanceFactor: 1.04, specs: [['Núcleos / hilos', '12 / 24'], ['Socket', 'AM5'], ['TDP', '170W']] }),
  makeProduct({ id: 'intel-core-i5-14400f', brand: 'Intel', category: 'Procesadores', name: 'Intel Core i5-14400F', description: '10 núcleos híbridos y 16 hilos para gaming de gama media.', builderNote: '10 núcleos · 65W · gaming equilibrado', price: 1690, image: '/products/builder-cpu.webp', socket: 'LGA1700', memoryType: 'DDR5', powerDraw: 95, performanceFactor: .88, recommended: true, specs: [['Núcleos / hilos', '10 / 16'], ['Socket', 'LGA1700'], ['Base', '65W']] }),
  makeProduct({ id: 'intel-core-i5-14600k', brand: 'Intel', category: 'Procesadores', name: 'Intel Core i5-14600K', description: '14 núcleos híbridos y alto turbo para gaming y streaming.', builderNote: '14 núcleos · 181W turbo · streaming', price: 2480, image: '/products/builder-cpu.webp', socket: 'LGA1700', memoryType: 'DDR5', powerDraw: 181, performanceFactor: .98, specs: [['Núcleos / hilos', '14 / 20'], ['Socket', 'LGA1700'], ['Turbo', '181W']] }),
  makeProduct({ id: 'intel-core-i9-14900k', brand: 'Intel', category: 'Procesadores', name: 'Intel Core i9-14900K', description: '24 núcleos híbridos para cargas profesionales y gaming extremo.', builderNote: '24 núcleos · 253W turbo · máximo rendimiento', price: 4550, image: '/products/builder-cpu.webp', socket: 'LGA1700', memoryType: 'DDR5', powerDraw: 253, performanceFactor: 1.06, specs: [['Núcleos / hilos', '24 / 32'], ['Socket', 'LGA1700'], ['Turbo', '253W']] }),

  makeProduct({ id: 'deepcool-ak400', brand: 'DeepCool', category: 'Refrigeración', name: 'DeepCool AK400', description: 'Disipador compacto de torre para procesadores de consumo medio.', builderNote: 'Aire · 180W · altura 155 mm', price: 390, image: '/products/ccl-cooler-v2.webp', sockets: ['AM5', 'LGA1700'], coolingCapacity: 180, coolerHeight: 155, powerDraw: 4, recommended: true, specs: [['Capacidad', '180W'], ['Altura', '155 mm'], ['Ventilador', '120 mm']] }),
  makeProduct({ id: 'noctua-nh-d15', brand: 'Noctua', category: 'Refrigeración', name: 'Noctua NH-D15 chromax.black', description: 'Doble torre silenciosa para procesadores de alto consumo.', builderNote: 'Doble torre · 250W · altura 165 mm', price: 1190, image: '/products/ccl-cooler-v2.webp', sockets: ['AM5', 'LGA1700'], coolingCapacity: 250, coolerHeight: 165, powerDraw: 6, specs: [['Capacidad', '250W'], ['Altura', '165 mm'], ['Ventiladores', '2 × 140 mm']] }),
  makeProduct({ id: 'corsair-h150i-360', brand: 'Corsair', category: 'Refrigeración', name: 'Corsair H150i 360', description: 'Refrigeración líquida AIO de 360 mm para CPUs exigentes.', builderNote: 'Líquida · 300W · radiador 360 mm', price: 1580, image: '/products/ccl-cooler-v2.webp', sockets: ['AM5', 'LGA1700'], coolingCapacity: 300, coolerHeight: 120, radiatorSize: 360, powerDraw: 18, specs: [['Tipo', 'AIO 360 mm'], ['Capacidad', '300W'], ['Ventiladores', '3 × 120 mm']] }),

  makeProduct({ id: 'corsair-vengeance-16gb', brand: 'Corsair', category: 'RAM', name: 'Corsair Vengeance DDR5 16GB', description: 'Kit 2×8GB para equipos gamer de entrada.', builderNote: '16GB · 5600MT/s · DDR5', price: 520, image: '/products/builder-ram.webp', memoryType: 'DDR5', capacity: 16, powerDraw: 6, specs: [['Capacidad', '16GB'], ['Velocidad', '5600MT/s'], ['Formato', 'DDR5']] }),
  makeProduct({ id: 'gskill-flare-x5-32gb', brand: 'G.Skill', category: 'RAM', name: 'G.Skill Flare X5 DDR5 32GB', description: 'Kit 2×16GB optimizado para AMD EXPO.', builderNote: '32GB · 6000MT/s · EXPO', price: 920, image: '/products/builder-ram.webp', memoryType: 'DDR5', capacity: 32, powerDraw: 9, recommended: true, specs: [['Capacidad', '32GB'], ['Velocidad', '6000MT/s'], ['Perfil', 'AMD EXPO']] }),
  makeProduct({ id: 'corsair-dominator-32gb', brand: 'Corsair', category: 'RAM', name: 'Corsair Dominator Titanium 32GB', description: 'Memoria DDR5 premium de baja latencia.', builderNote: '32GB · 6400MT/s · CL32', price: 1280, image: '/products/builder-ram.webp', memoryType: 'DDR5', capacity: 32, powerDraw: 11, specs: [['Capacidad', '32GB'], ['Velocidad', '6400MT/s'], ['Latencia', 'CL32']] }),
  makeProduct({ id: 'kingston-fury-ddr5-64gb', brand: 'Kingston', category: 'RAM', name: 'Kingston Fury Beast DDR5 64GB', description: 'Kit 2×32GB para edición, streaming y multitarea intensiva.', builderNote: '64GB · 6000MT/s · creación', price: 1700, image: '/products/builder-ram.webp', memoryType: 'DDR5', capacity: 64, powerDraw: 14, specs: [['Capacidad', '64GB'], ['Velocidad', '6000MT/s'], ['Formato', '2 × 32GB']] }),
  makeProduct({ id: 'gskill-trident-z5-96gb', brand: 'G.Skill', category: 'RAM', name: 'G.Skill Trident Z5 DDR5 96GB', description: 'Kit 2×48GB para estaciones de creación avanzada.', builderNote: '96GB · 6400MT/s · trabajo profesional', price: 2590, image: '/products/builder-ram.webp', memoryType: 'DDR5', capacity: 96, powerDraw: 18, specs: [['Capacidad', '96GB'], ['Velocidad', '6400MT/s'], ['Formato', '2 × 48GB']] }),

  makeProduct({ id: 'asus-rtx-4060-ti', brand: 'ASUS', category: 'Tarjetas gráficas', name: 'ASUS Dual GeForce RTX 4060 Ti 8GB', description: 'Gráfica eficiente para 1080p de alta frecuencia.', builderNote: '8GB · 160W · 1080p competitivo', price: 3790, image: '/products/builder-gpu.webp', recommendedWattage: 550, powerDraw: 160, performanceIndex: 1.18, length: 227, recommended: true, specs: [['Memoria', '8GB GDDR6'], ['Consumo', '160W'], ['Longitud', '227 mm']] }),
  makeProduct({ id: 'gigabyte-rtx-4070-super', brand: 'Gigabyte', category: 'Tarjetas gráficas', name: 'Gigabyte RTX 4070 SUPER Gaming OC 12GB', description: 'Potencia QHD con DLSS 3 y refrigeración de triple ventilador.', builderNote: '12GB · 220W · 1440p ultra', price: 6250, image: '/products/builder-gpu.webp', recommendedWattage: 650, powerDraw: 220, performanceIndex: 1.67, length: 300, specs: [['Memoria', '12GB GDDR6X'], ['Consumo', '220W'], ['Longitud', '300 mm']] }),
  makeProduct({ id: 'sapphire-rx-7700-xt', brand: 'Sapphire', category: 'Tarjetas gráficas', name: 'Sapphire Radeon RX 7700 XT 12GB', description: 'Rendimiento sólido para 1440p con 12GB de memoria.', builderNote: '12GB · 245W · 1440p', price: 4690, image: '/products/builder-gpu.webp', recommendedWattage: 700, powerDraw: 245, performanceIndex: 1.48, length: 280, specs: [['Memoria', '12GB GDDR6'], ['Consumo', '245W'], ['Longitud', '280 mm']] }),
  makeProduct({ id: 'powercolor-rx-7800-xt', brand: 'PowerColor', category: 'Tarjetas gráficas', name: 'PowerColor Radeon RX 7800 XT 16GB', description: '16GB de memoria y alto rendimiento para QHD.', builderNote: '16GB · 263W · 1440p ultra', price: 5450, image: '/products/builder-gpu.webp', recommendedWattage: 750, powerDraw: 263, performanceIndex: 1.62, length: 322, specs: [['Memoria', '16GB GDDR6'], ['Consumo', '263W'], ['Longitud', '322 mm']] }),
  makeProduct({ id: 'msi-rtx-4080-super', brand: 'MSI', category: 'Tarjetas gráficas', name: 'MSI GeForce RTX 4080 SUPER 16GB', description: 'Gráfica de gama alta para 4K y creación acelerada.', builderNote: '16GB · 320W · 4K', price: 10500, image: '/products/builder-gpu.webp', recommendedWattage: 850, powerDraw: 320, performanceIndex: 2.18, length: 322, specs: [['Memoria', '16GB GDDR6X'], ['Consumo', '320W'], ['Longitud', '322 mm']] }),
  makeProduct({ id: 'sapphire-rx-7900-xtx', brand: 'Sapphire', category: 'Tarjetas gráficas', name: 'Sapphire Radeon RX 7900 XTX 24GB', description: '24GB de memoria para gaming 4K y creación pesada.', builderNote: '24GB · 355W · 4K nativo', price: 9800, image: '/products/builder-gpu.webp', recommendedWattage: 850, powerDraw: 355, performanceIndex: 2.08, length: 313, specs: [['Memoria', '24GB GDDR6'], ['Consumo', '355W'], ['Longitud', '313 mm']] }),

  makeProduct({ id: 'crucial-p3-plus-1tb', brand: 'Crucial', category: 'SSD', name: 'Crucial P3 Plus NVMe 1TB', description: 'SSD PCIe 4.0 accesible para sistema y juegos.', builderNote: '1TB · 5000MB/s · PCIe 4.0', price: 520, image: '/products/builder-ssd.webp', capacity: 1, powerDraw: 5, recommended: true, specs: [['Capacidad', '1TB'], ['Lectura', '5000 MB/s'], ['Interfaz', 'PCIe 4.0']] }),
  makeProduct({ id: 'wd-black-sn850x-1tb', brand: 'Western Digital', category: 'SSD', name: 'WD Black SN850X 1TB', description: 'NVMe de alto rendimiento optimizado para gaming.', builderNote: '1TB · 7300MB/s · gaming', price: 720, image: '/products/builder-ssd.webp', capacity: 1, powerDraw: 7, specs: [['Capacidad', '1TB'], ['Lectura', '7300 MB/s'], ['Interfaz', 'PCIe 4.0']] }),
  makeProduct({ id: 'crucial-t500-2tb', brand: 'Crucial', category: 'SSD', name: 'Crucial T500 NVMe 2TB', description: 'SSD rápido para gaming y flujos creativos.', builderNote: '2TB · 7400MB/s · PCIe 4.0', price: 1190, image: '/products/builder-ssd.webp', capacity: 2, powerDraw: 8, specs: [['Capacidad', '2TB'], ['Lectura', '7400 MB/s'], ['Interfaz', 'PCIe 4.0']] }),
  makeProduct({ id: 'samsung-990-pro-4tb', brand: 'Samsung', category: 'SSD', name: 'Samsung 990 PRO NVMe 4TB', description: 'Gran capacidad y rendimiento sostenido para bibliotecas extensas.', builderNote: '4TB · 7450MB/s · alto rendimiento', price: 2560, image: '/products/builder-ssd.webp', capacity: 4, powerDraw: 9, specs: [['Capacidad', '4TB'], ['Lectura', '7450 MB/s'], ['Interfaz', 'PCIe 4.0']] }),
  makeProduct({ id: 'wd-black-sn850x-4tb', brand: 'Western Digital', category: 'SSD', name: 'WD Black SN850X 4TB', description: 'Almacenamiento NVMe amplio para juegos y producción.', builderNote: '4TB · 7300MB/s · gran biblioteca', price: 2380, image: '/products/builder-ssd.webp', capacity: 4, powerDraw: 9, specs: [['Capacidad', '4TB'], ['Lectura', '7300 MB/s'], ['Interfaz', 'PCIe 4.0']] }),

  makeProduct({ id: 'corsair-rm650e', brand: 'Corsair', category: 'Fuentes de poder', name: 'Corsair RM650e 650W Gold', description: 'Fuente modular compacta para equipos de gama media.', builderNote: '650W · Gold · modular', price: 790, image: '/products/ccl-psu-v2.webp', wattage: 650, specs: [['Potencia', '650W'], ['Certificación', '80 Plus Gold'], ['Cableado', 'Modular']] }),
  makeProduct({ id: 'seasonic-focus-750', brand: 'Seasonic', category: 'Fuentes de poder', name: 'Seasonic Focus GX-750 Gold', description: 'Fuente modular estable con diez años de garantía.', builderNote: '750W · Gold · modular', price: 980, image: '/products/ccl-psu-v2.webp', wattage: 750, specs: [['Potencia', '750W'], ['Certificación', '80 Plus Gold'], ['Cableado', 'Modular']] }),
  makeProduct({ id: 'corsair-rm1000x', brand: 'Corsair', category: 'Fuentes de poder', name: 'Corsair RM1000x 1000W Gold', description: 'Fuente de alta capacidad para GPUs entusiastas.', builderNote: '1000W · Gold · ATX 3.0', price: 1550, image: '/products/ccl-psu-v2.webp', wattage: 1000, specs: [['Potencia', '1000W'], ['Certificación', '80 Plus Gold'], ['Estándar', 'ATX 3.0']] }),
  makeProduct({ id: 'bequiet-dark-power-1200', brand: 'be quiet!', category: 'Fuentes de poder', name: 'be quiet! Dark Power 13 1200W', description: 'Fuente Titanium para estaciones extremas y múltiples expansiones.', builderNote: '1200W · Titanium · ATX 3.0', price: 2490, image: '/products/ccl-psu-v2.webp', wattage: 1200, specs: [['Potencia', '1200W'], ['Certificación', '80 Plus Titanium'], ['Estándar', 'ATX 3.0']] }),
]
